name: Laravel CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/server.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP dependencies
        working-directory: ./server
        run: composer install --no-scripts --prefer-dist --optimize-autoloader

      - name: Run tests
        working-directory: ./server
        run: vendor/bin/phpunit --exclude-group google

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      ROOT_DIR: /var/www/pigment
      APP_DIR: /var/www/pigment/api
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      RELEASE_DIR: /var/www/pigment/api/releases/${{ github.sha }}

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: ROOT_DIR,RELEASE_DIR,APP_DIR
          script: |
            set -e
            export ROOT_DIR=$ROOT_DIR
            export RELEASE_DIR=$RELEASE_DIR
            
            cd $ROOT_DIR
            mkdir -p $RELEASE_DIR
            sudo chown www-data:www-data $RELEASE_DIR
            git clone --depth 1 https://github.com/colinxr/pigment.git repo
            cd repo
            
            git reset --hard HEAD
            
            rm -rf server/storage
            cp -rpa server/* $RELEASE_DIR
            
            ln -s /var/www/pigment/.env $RELEASE_DIR/.env 
            ln -s /var/www/pigment/storage $RELEASE_DIR/
            ls -la $RELEASE_DIR/storage
            
            cd $ROOT_DIR && rm -rf repo

      - name: Run Migrations
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: ROOT_DIR,RELEASE_DIR,APP_DIR
          script: |
            export ROOT_DIR=$ROOT_DIR
            export RELEASE_DIR=$RELEASE_DIR
            
            cd $RELEASE_DIR 
            
            composer install --prefer-dist --no-scripts --no-dev -q -o;
            
            php artisan config:cache
            php artisan migrate --force
            php artisan optimize

      - name: Symlink Release & Set Up Permissions
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: ROOT_DIR,RELEASE_DIR,APP_DIR
          script: |
            export RELEASE_DIR=$RELEASE_DIR
            
            sudo chmod -R 755 $RELEASE_DIR
            sudo find $RELEASE_DIR -type f -exec chmod 644 {} \;
            sudo chmod 600 $RELEASE_DIR/.env

            rm -rf /var/www/pigment/api/current
            ln -s $RELEASE_DIR /var/www/pigment/api/current
            ls -la /var/www/pigment/api/current
